### ISSUE TITLE
Create Footer component 

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#68]
# UI

<img width="1419" alt="Screen Shot 2562-10-24 at 09 40 46" src="https://user-images.githubusercontent.com/16553272/67475793-12e93c00-f681-11e9-9bc2-cddac16153b1.png">

# Usage

Describe how to use the component

```html
<!-- Footer with text branner,   -->
<Footer banner="Footer component" copyright="© 2019 Component" policy="{title: 'Privacy & Cookie Policy', link: 'https://...' }"  />

<!-- Footer with image branner -->
<Footer banner="./image.svg" copyright="© 2019 Component" policy="{title: 'Privacy & Cookie Policy', link: 'https://...' }"  />

<!-- Footer with slot menue -->
<Footer banner="./image.svg" copyright="© 2019 Component" policy="{title: 'Privacy & Cookie Policy', link: 'https://...' }"  categories="[ {key: xxx,title: 'xxx' to: 'xxx' }, ... ]">
  <template v-slot:column_xx="{ item }">
      <a :href="{item.to}" target="_blank">{{item.title}}</a>
   </template>
   <template v-slot:column_xx="{ item }">
      <a :href="{item.to}" >{{item.title}}</a>
   </template>
  ...
</Footer>

<!-- Footer with custom menue -->
<Footer banner="./image.svg" >
   <h1>Footer components</h1>
   <a href="/">XXX</>
</Footer>
...
```

# Properties

List all the properties needed for the component:
- banner: String (required -> banner to display on the footer
- copyright: String (optional) -> description  to display on the footer
- policy: Object (optional) -> policy  to display on the footer
- categories: Array (optional) -> policy  to display on the footer

# Slots

# Events

none

**Comment by antho1404** [comment]
Few issues:

- what's branner? Probably mean banner?
- copyright should be in one word
- some types are missing in the properties
- products, develops, foundations, token: it's not clear what they are and that's not what we discussed last time, we shouldn't have a property on a component that is specific to the content. These properties should disappear.
- I don't see the point of having this default slot and I also don't understand how it will be displayed? first column? instead of the logo? in the copyright?
- slots based on the name of the category are not documented.

**Comment by blackinno** [comment]
Done.
