### ISSUE TITLE
Create Group component

### ISSUE THREAD

**Issue by blackinno** [mesg-foundation/mesg-components#70]
# UI

![Screen Shot 2562-10-25 at 10 17 59](https://user-images.githubusercontent.com/16553272/67540989-8a66ac00-f711-11e9-9b90-29f936c777af.png)

# Usage

Describe how to use the component

```html
<!-- Group component with type button -->
<Group type="button"  items="[ {title: 'xxx', icon: 'fal fa-xxx' }, ... ]" v-model="input"  value="xxx" />

<!-- Group component with type selected -->
<Group type="selected"  items="[ {title: 'xxx', icon: 'fal fa-xxx' }, ... ]" v-model="input"  value="xxx" />

<!-- Group component with type radio -->
<Group type="radio"  items="[ {title: 'xxx', icon: 'fal fa-xxx' }, ... ]" v-model="input"  value="xxx" />

<!-- Group component with type tab -->
<Group type="tab"  items="[ {title: 'xxx', icon: 'fal fa-xxx' }, ... ]" v-model="input"  value="xxx" />

...
```

# Properties

List all the properties needed for the component:

- items: Array (required) -> display items on the button group
- type: String <`"buttons" | "select" | "radio" | "tab"`> (required)
- value: `Any`:   value to match the value in the item list

# Slots

none.

# Events
 - input: `Any`: the value of the selected element

**Comment by antho1404** [comment]
I wonder if this component cannot be done more generic. This is a component that let you have a choice between X possibilities so why not have this and create a `Choice` component with the following.

Properties:
- **value**: `Any`: value to match the value in the item list
- **items**: `Array<{ text: String, value: Any, icon?: String }>`: list of items to display with their values
- **type**: `"buttons" | "select" | "radio" | "tab"`: type of rendering for the choice, this can be a button like this component or a select box, radio tab... For now, we can support only button group

Events:
- **input**: `Any`: the value of the selected element

**value property and input event are used in order to bind inputs with `v-model` https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components**

**Comment by blackinno** [comment]
@antho1404 I see. I will fix the `Group components` to this spec.

**Comment by blackinno** [comment]
Done.
